inherit: false

before_commands:
  - composer install

tools:
  php_code_coverage:
    config_path: ~
    test_command: phpunit
    only_changesets: true
    enabled: true
    filter:
      paths: [src/php]
      excluded_paths: []

  php_code_sniffer:
     extensions:
       - php
     command: phpcs
     enabled: true
     filter:
       paths: [src/php]
       excluded_paths: []
     config:
       standard: PSR2
       sniffs: []
       severity: ~
       error_severity: ~
       warning_severity: ~
       tab_width: ~
       encoding: UTF-8

  php_cpd:
    command: phpcpd
    min_lines: 5
    min_tokens: 70
    excluded_dirs: [src/tests, vendor]
    names:
      - "*.php"
    enabled: true
    filter:
      paths: [src/php]
      excluded_paths: []

  php_cs_fixer:
    extensions:
      - php
    command: php-cs-fixer
    enabled: false
    filter:
      paths: [src/php, src/tests]
      excluded_paths: []
    config:
      level: psr2
      fixers: []

  php_mess_detector:
    extensions:
      - php
    command: phpmd
    enabled: true
    filter:
      paths: [src/php]
      excluded_paths: []
    config:
      rulesets:
        - controversial
        - codesize
        - design
        - naming
        - unused

  php_analyzer: true

  sensiolabs_security_checker: true
